name: "Java"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - name: "Give gradlew execute permission"
        run: chmod +x gradlew

      - name: "Build project"
        run: ./gradlew build

# CI